name: Build and Verify

on:
  pull_request: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Baiju Muthukadan"
          git config user.email "baiju.m.mail@gmail.com"

      - name: Verify package
        run: |
          echo ${{ github.actor }}
